language: node_js
sudo: false

node_js:
  - "8.9.1"

notifications:
  email:
    on_success: never
    on_failure: change

after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
